services:
  - type: web
    name: backdoor-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        generateValue: true
      - key: TOGETHER_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: MCP_ENABLED
        value: "true"
      - key: MCP_LOG_LEVEL
        value: "INFO"
      - key: VSCODE_SERVER_PATH
        value: "/usr/bin/code-server"
    healthCheckPath: /api/health
  
  - type: postgres
    name: backdoor-db
    plan: free
    ipAllowList: []

databases:
  - name: backdoor-db
    plan: free
